/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.uap.lfw.md;

/**
 * <b> 在此处简要描述此接口的功能 </b>
 * <p>
 *     在此处添加此接口的描述信息
 * </p>
 * 创建日期:2010-06-21 16:15:42
 * @author 
 * @version NCPrj ??
 */
public interface LfwTabcodeItf{
			
	/**
	 * 属性tabcode的Getter方法.
	 * 创建日期:2010-06-21 16:15:42
	 * @return java.lang.String
	 */
	public java.lang.String getTabcode ();

} 
